### PR TITLE
Fix serialization of collections with Giraffe

### PR DESCRIPTION
**Pull request by johannesegger**
Failed with an error like "Could not determine JSON object type for type System.Int32[]" when trying to use the compile time type instead of the runtime type.
See also https://github.com/MangelMaxime/Thoth/commit/8d3cdf5b7c692b55b0b2efb09a53d40b8867d376

If you want to avoid boxing I think the if condition could also be something like `not typeof<'T>.IsValueType && EqualityComparer<'T>.Default.Equals(o, Unchecked.defaultof<'T>))` but that's even more ugly IMO.

### CODE REVIEW

**Comment by johannesegger** [comment]
Uhh, that breaks if Thoth.Json.Net >= 3.4.0 is used because `generateEncoderCached` was moved to a new type `LowLevel`. Do you want to update the min version of Thoth.Json.Net to the current version 3.5.1?

**Comment by MangelMaxime** [comment]
Hello @johannesegger yes, we should indeed update the min version of Thoth.Json.Net.

Is this PR ready to be merged and released? I don't have yet tests on this repos to check that everything works properly that's why I am asking :)

**Comment by johannesegger** [comment]
I didn't update the version of Thoth.Json.Giraffe, otherwise it should be fine 🤞.
Should I set the version to 2.2.0?

**Comment by johannesegger** [comment]
Version and changelog is updated, if you're ready you can merge and run the build/release.

**Comment by MangelMaxime** [comment]
Thank you, I just released the new version. It should be available soon on NuGet.

**Pull request merged**
