### PR TITLE
Avoid "Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true." error

### PR DESCRIPTION
**Pull request by MaxDeg**
With aspnet core 3.X calling sync Write method on Response body throw an exception.

Flushing JsonTextWriter asynchronously avoid Dispose method to doing it sync.
Resulting in the following error: "System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true."

### CODE REVIEW

**Comment by MangelMaxime** [comment]
When running the tests via `dotnet run`, the process hang for ever and never exit.

This is a problem because, then I can automate the tests do you have this problem?

**Comment by MaxDeg** [comment]
Not that I know. I will check that tomorrow. Are you running them on Windows or Linux?

**Comment by MangelMaxime** [comment]
I was running on windows

**Comment by MaxDeg** [comment]
I added dependencies to support `dotnet test` and dispose the host in tests to avoid hanging of expecto process.

**Comment by MangelMaxime** [comment]
Thank you @MaxDeg and sorry for taking so long for merging and releasing the PR

**Comment by MaxDeg** [comment]
You're welcome 😊 Glad to contribute.

**Pull request merged**
