### PR TITLE
Try cache otherwise generate the encoder on place

### PR DESCRIPTION
**Pull request by tforkmann**
As discuss in Gitter this fixes passing the type none

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @tforkmann ,

I merged your branch but after looking at the code I think I discovered another solution to our problem. So I hard reset the master branch to it's previous state.

Could you please try the following lines in your project?

```fs
let encoder = Encode.Auto.generateEncoderCached<'T>(?isCamelCase=isCamelCase, ?extra=extra)
```

and 

```fs
let t = typeof<'T>
let encoder = Encode.Auto.generateEncoderCached(t, ?isCamelCase=isCamelCase, ?extra=extra)
```

I made some manual test using `fsi` but I prefer to make sure they work before making a release.

If that version works, they should, in theory, allow us to always use the `cached` version of the decoder which can be a small performance improvement for your application :)

**Comment by tforkmann** [comment]
Sorry was on vacation. Will check on Monday morning!

**Comment by tforkmann** [comment]
Good Morning :)
So the both lines are working for my specific problem!

**Comment by MangelMaxime** [comment]
Thank you for confirming I will make a release with one of the solution then :)

**Comment by MangelMaxime** [comment]
Hello :)

The fix should be available in version 2.1.0

**Comment by tforkmann** [comment]
Can confirm 2.1.0 is working! thank you very much!

**Pull request merged**
