### PR TITLE
Fix Sequence serialization not writing a close `]`

### PR DESCRIPTION
**Pull request by ImaginaryDevelopment**
I've written 4 tests, 3 of which failed (the 3 that involved sequences). I also found the offending line and managed to show the tests all passing.

### CODE REVIEW

**Comment by ImaginaryDevelopment** [comment]
closes #10

**Comment by MangelMaxime** [comment]
Thank you for the PR, I am releasing a new version.

For reference, this PR doesn't solve #10.

In #10 the problem is when trying to use Auto coders with a `'T seq` type. The problem, in this case, is coming from Thoth.Json.Net, not Thoth.Json.Giraffe. :)

**Comment by ImaginaryDevelopment** [comment]
Thank you, One question though, if it doesn't solve #10 then why does the test titled `SerializationSeq` pass with this change?

**Comment by MangelMaxime** [comment]
Hum... I was going to say that it's because it's using a manual coder but you are actually generating it...

But I am sure that Thoth.Json.Net doesn't support `'T seq` as it is disabled right now:

[Source encoder](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Encode.fs#L493-L494)
[Sourcde decoder](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Decode.fs#L1187-L1189)

The honest answer is I don't know 🤷‍♂️ and need to investigate more. Or I could just release the fix for Thoth.Json.Net as it is available in a seprate branch with others changes which hold me back a bit.

**Pull request merged**
