### PR TITLE
remove setStatusCode and update commets

### PR DESCRIPTION
**Pull request by MaxDeg**
Pull Request for issue #5

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Thank you for the PR.

This is released in version 3.0.0

**Comment by MaxDeg** [comment]
Version 3.0.0 is not available in nuget?

**Comment by MangelMaxime** [comment]
I think I miss again the release process... It seems to happen often to me, I need to check this problem.

Will release it tomorrow, I don't have access to the correct computer right now.

**Comment by MangelMaxime** [comment]
It should be available soon, I checked this time it's appearing in NuGet processing queue.

**Pull request merged**
