### PR TITLE
Update to .NET 6

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @forki,

does Thoth.Json.Net needs an update to or is `net5.0` libraries compatible when consumed from a `net6.0` project?

**Comment by forki** [comment]
Good question. Does it use Ply or Taskbuilder.fs?

**Comment by MangelMaxime** [comment]
No it doesn't its dependencies are minimal:

image

Just using  `Newtonsoft.Json` to get the JSON parsing done.

**Comment by MangelMaxime** [comment]
This has been released as version 6.0.0-beta-001

**Pull request merged**
